name: PR stats
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  stats:
    uses: MihaiStreames/tokount-action/.github/workflows/pr-stats.yml@v1
    with:
      exclude: target,data
    permissions:
      pull-requests: write
